name: Generate Sponsors README
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.READER_PAT }}
          file: 'README.md'
          template: '* [{{{ name }}}]({{{ url }}}) - {{{ login }}}'
          organization: true

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: '.'
          token: ${{ secrets.WRITER_PAT }}
